version: '3'


services:
  testeos:
    build:
      context: .
    image: ghcr.io/reflejar/pis-shiny:latest
    volumes:
      - ./apps/testeos:/srv/shiny-server
    ports:
      - "3838:3838"
    environment:
      - APP_CONFIG=testeos